/**
 * 美国行业轮动研究分期。
 *
 * 边界优先采用四类可复核转折：NBER 周期拐点、FOMC 政策切换、信用/流动性事件、
 * 以及足以改变行业定价主线的市场拐点。它们是研究用的情境切片，不是用事后行业收益
 * 反推出来的最优回测窗口。
 */
export type SectorHistoricalEvent = {
  date: string;
  title: string;
  impact: string;
};

export type SectorHistoricalPeriod = {
  id: string;
  label: string;
  shortLabel: string;
  start: string;
  end: string;
  macro: string;
  regime: {
    growth: string;
    inflation: string;
    policy: string;
    credit: string;
  };
  events: readonly SectorHistoricalEvent[];
  mechanism: string;
  expectedLeaders: readonly string[];
  caveat?: string;
};

export const SECTOR_HISTORICAL_PERIODS: readonly SectorHistoricalPeriod[] = [
  {
    id: "dotcom-melt-up",
    label: "亚洲危机余波、宽松托底与互联网融涨",
    shortLabel: "1998.12–2000.03",
    start: "1998-12-16",
    end: "2000-03-24",
    macro: "外部危机缓和、美国生产率叙事升温，低通胀与充裕流动性推动风险偏好走向极端；1999 年后 Fed 重新收紧。",
    regime: { growth: "强劲并加速", inflation: "偏低、后期抬头", policy: "1998 降息托底，1999–2000 加息", credit: "资本市场融资极度宽松" },
    events: [
      { date: "1998-09/11", title: "危机式降息", impact: "Fed 连续三次降息，压低尾部风险并恢复市场流动性。" },
      { date: "2000-03-24", title: "互联网泡沫见顶", impact: "估值和融资条件同时转向，久期最长的资产先失去支撑。" },
    ],
    mechanism: "贴现率低、融资易得和网络效应叙事共同抬升长久期估值，科技与可选消费最受益；当政策转紧，盈利兑现不足会放大回撤。",
    expectedLeaders: ["信息技术", "可选消费", "通信服务"],
  },
  {
    id: "dotcom-unwind",
    label: "科技泡沫破裂与盈利预期坍塌",
    shortLabel: "2000.03–2001.03",
    start: "2000-03-24",
    end: "2001-03-19",
    macro: "企业 IT 投资和利润预期快速下修，财富效应逆转，经济从高增长滑向 NBER 认定的衰退起点。",
    regime: { growth: "快速减速", inflation: "温和回落", policy: "先紧后于 2001 年急转降息", credit: "股权融资关闭、信用开始分层" },
    events: [
      { date: "2000-05-16", title: "政策利率升至 6.5%", impact: "融资成本与估值压力在泡沫破裂后继续叠加。" },
      { date: "2001-01-03", title: "紧急降息 50bp", impact: "确认增长风险已压过通胀风险，但无法立刻修复资本开支。" },
    ],
    mechanism: "需求下修和估值压缩双杀高资本开支行业；现金流稳定、股息可见的必需消费、公用事业和医疗相对占优。",
    expectedLeaders: ["必需消费", "公用事业", "医疗保健"],
  },
  {
    id: "recession-911-scandals",
    label: "衰退、9·11 与公司治理危机",
    shortLabel: "2001.03–2002.10",
    start: "2001-03-19",
    end: "2002-10-09",
    macro: "浅衰退叠加恐袭、地缘冲突和安然/世通等会计丑闻，风险溢价与盈利不确定性长期高位。",
    regime: { growth: "衰退后弱复苏", inflation: "低位", policy: "连续降息至 1.25%", credit: "风险溢价高、治理信任受损" },
    events: [
      { date: "2001-09-11", title: "恐袭与市场停摆", impact: "流动性需求激增，航空、保险、旅游和周期需求受压。" },
      { date: "2002-07", title: "公司会计丑闻集中暴露", impact: "投资者提高股权风险溢价，更偏好资产负债表和现金流质量。" },
    ],
    mechanism: "降息只能缓冲需求，不能立即重建信任；防御行业依靠稳定终端需求相对抗跌，金融与科技继续消化坏账和过剩产能。",
    expectedLeaders: ["必需消费", "医疗保健", "公用事业"],
  },
  {
    id: "one-percent-reflation",
    label: "1% 利率、财政刺激与早期再通胀",
    shortLabel: "2002.10–2004.06",
    start: "2002-10-09",
    end: "2004-06-30",
    macro: "衰退后库存和利润修复，政策利率降至 1%，减税与住房需求共同托举名义增长。",
    regime: { growth: "由弱转强", inflation: "低位回升", policy: "超宽松货币 + 扩张财政", credit: "按揭与企业融资改善" },
    events: [
      { date: "2003-06-25", title: "联邦基金利率降至 1%", impact: "实际利率低位延长，住房和杠杆需求快速扩张。" },
      { date: "2003-H2", title: "企业利润与投资复苏", impact: "风险溢价下降，周期行业从低基数重估。" },
    ],
    mechanism: "增长改善、曲线较陡和信用扩张利好金融、工业与可选消费；商品需求回升开始改善能源和材料盈利。",
    expectedLeaders: ["金融", "工业", "可选消费", "材料"],
  },
  {
    id: "measured-tightening-housing",
    label: "渐进加息、住房繁荣与全球商品周期",
    shortLabel: "2004.06–2006.06",
    start: "2004-06-30",
    end: "2006-06-29",
    macro: "Fed 以“可控节奏”连续加息，但信贷条件仍宽，住房、杠杆和中国驱动的商品需求同步扩张。",
    regime: { growth: "稳健扩张", inflation: "上行", policy: "17 次 25bp 加息", credit: "抵押贷款与结构化信用繁荣" },
    events: [
      { date: "2004-06-30", title: "加息周期启动", impact: "短端利率上升，但渐进路径未立即收紧风险资产融资。" },
      { date: "2005–2006", title: "住房与商品价格加速", impact: "银行、建筑链、能源和材料盈利获得顺周期支撑。" },
    ],
    mechanism: "名义增长与贷款量增长抵消部分融资成本上升，金融和资源股受益；收益率曲线逐步变平，为下一阶段埋下压力。",
    expectedLeaders: ["能源", "材料", "金融", "工业"],
  },
  {
    id: "late-cycle-inversion",
    label: "利率倒挂、住房转弱与晚周期冲顶",
    shortLabel: "2006.06–2007.10",
    start: "2006-06-29",
    end: "2007-10-09",
    macro: "政策利率停在 5.25%，收益率曲线倒挂，住房活动先行下行，但全球增长和企业盈利暂时掩盖信用裂纹。",
    regime: { growth: "高位放缓", inflation: "仍偏高", policy: "高利率平台", credit: "表面宽松、次贷内部恶化" },
    events: [
      { date: "2006-H2", title: "住房市场转弱", impact: "住宅投资、按揭质量和金融中介资产负债表开始承压。" },
      { date: "2007-08", title: "次贷压力进入货币市场", impact: "信用风险从局部贷款扩散到融资与证券化渠道。" },
    ],
    mechanism: "晚周期中资源与资本品仍靠全球需求冲顶，银行净息差和资产质量却开始恶化；防御行业的相对价值上升。",
    expectedLeaders: ["能源", "材料", "工业", "必需消费"],
  },
  {
    id: "subprime-credit-break",
    label: "次贷扩散、贝尔斯登与信用断裂",
    shortLabel: "2007.10–2008.09",
    start: "2007-10-09",
    end: "2008-09-15",
    macro: "房价下跌触发证券化资产减值，银行去杠杆压缩信贷；Fed 降息但信用利差与融资压力继续恶化。",
    regime: { growth: "由放缓转衰退", inflation: "油价推动表面高企", policy: "快速降息与定向流动性工具", credit: "系统性收紧" },
    events: [
      { date: "2007-12", title: "NBER 衰退起点", impact: "收入、就业和工业活动开始广泛收缩。" },
      { date: "2008-03", title: "贝尔斯登救助", impact: "经纪商融资与交易对手风险成为核心定价变量。" },
    ],
    mechanism: "金融资产负债表风险主导行业差异；能源在油价见顶前仍有盈利支撑，必需消费、医疗和公用事业靠稳定需求相对抗跌。",
    expectedLeaders: ["必需消费", "医疗保健", "公用事业", "能源"],
  },
  {
    id: "lehman-panic-qe1",
    label: "雷曼冲击、全球去杠杆与 QE1",
    shortLabel: "2008.09–2009.03",
    start: "2008-09-15",
    end: "2009-03-09",
    macro: "批发融资市场冻结、全球贸易与工业生产急坠，美元荒和强制去杠杆压倒传统基本面。",
    regime: { growth: "深度收缩", inflation: "从高位急降", policy: "零利率、TARP、QE1", credit: "冻结后靠公共资产负债表接管" },
    events: [
      { date: "2008-09-15", title: "雷曼破产", impact: "交易对手与流动性风险全面系统化，相关性急升。" },
      { date: "2008-11/2009-03", title: "QE1 宣布并扩容", impact: "公共部门开始压低期限与按揭风险溢价。" },
    ],
    mechanism: "现金和融资可得性比盈利更重要，几乎所有行业绝对收益都可能为负；稳定需求、高股息仅提供相对保护。",
    expectedLeaders: ["必需消费", "医疗保健", "公用事业"],
  },
  {
    id: "qe1-early-recovery",
    label: "压力测试、QE1 与深衰退后的抢跑",
    shortLabel: "2009.03–2010.04",
    start: "2009-03-09",
    end: "2010-04-23",
    macro: "金融体系尾部风险下降，库存周期反弹、信用利差压缩，市场领先实体经济确认复苏。",
    regime: { growth: "从深衰退转复苏", inflation: "低位", policy: "零利率 + QE1 + 财政刺激", credit: "从冻结转快速修复" },
    events: [
      { date: "2009-05", title: "银行压力测试结果公布", impact: "资本缺口更透明，金融尾部风险显著下降。" },
      { date: "2009-06", title: "NBER 衰退结束", impact: "库存和生产进入低基数恢复阶段。" },
    ],
    mechanism: "信用 beta 和经营杠杆主导反弹，金融、可选消费、工业与材料往往从极低估值中获得最大弹性。",
    expectedLeaders: ["金融", "可选消费", "工业", "材料"],
  },
  {
    id: "euro-crisis-qe2",
    label: "欧债危机、QE2 与美国主权评级冲击",
    shortLabel: "2010.04–2011.10",
    start: "2010-04-23",
    end: "2011-10-03",
    macro: "美国复苏失去部分动能，欧元区主权风险与财政紧缩提高全球尾部风险；QE2 只能阶段性压低金融条件。",
    regime: { growth: "复苏放缓", inflation: "先升后降", policy: "QE2、零利率前瞻指引", credit: "欧债风险反复冲击美元信用市场" },
    events: [
      { date: "2010-11", title: "QE2 启动", impact: "期限溢价下行、美元走弱，阶段性支持风险资产和商品。" },
      { date: "2011-08", title: "美国评级下调与欧债升级", impact: "避险需求上升，周期盈利预期再度下修。" },
    ],
    mechanism: "宏观不确定性和长端利率下行提升防御、高股息与稳定现金流相对吸引力；金融受欧洲敞口和低利率压制。",
    expectedLeaders: ["公用事业", "必需消费", "医疗保健"],
  },
  {
    id: "twist-qe3-recovery",
    label: "扭转操作、QE3 与住房就业修复",
    shortLabel: "2011.10–2013.05",
    start: "2011-10-03",
    end: "2013-05-22",
    macro: "欧洲尾部风险缓和，美国住房、就业和消费逐步修复；长期利率被资产购买和期限置换压低。",
    regime: { growth: "温和改善", inflation: "受控", policy: "Operation Twist + QE3", credit: "按揭与企业信用改善" },
    events: [
      { date: "2011-09", title: "扭转操作", impact: "通过延长资产组合久期压低长端融资成本。" },
      { date: "2012-09/12", title: "开放式 QE3", impact: "资产购买与就业改善挂钩，降低政策提前退出风险。" },
    ],
    mechanism: "低贴现率叠加盈利恢复有利可选消费、金融和成长股；住房链改善增强银行资产质量和居民财富效应。",
    expectedLeaders: ["可选消费", "金融", "信息技术", "工业"],
  },
  {
    id: "taper-normalization",
    label: "Taper 冲击、财政拖累消退与扩张延续",
    shortLabel: "2013.05–2014.06",
    start: "2013-05-22",
    end: "2014-06-30",
    macro: "市场开始定价购债减速，长端收益率上行；美国私人需求仍扩张，财政拖累逐步减轻。",
    regime: { growth: "温和扩张", inflation: "低位稳定", policy: "QE 减码预期到实际减码", credit: "总体宽松、利率敏感部门分化" },
    events: [
      { date: "2013-05-22", title: "Taper 讨论公开化", impact: "期限溢价快速回升，高股息与新兴市场承压。" },
      { date: "2013-12", title: "正式启动减码", impact: "政策退出变得可预测，增长确认抵消部分利率冲击。" },
    ],
    mechanism: "利率上行压制公用事业和高股息久期资产，金融受益于曲线和贷款改善，周期行业依赖增长兑现。",
    expectedLeaders: ["金融", "工业", "可选消费", "信息技术"],
  },
  {
    id: "dollar-oil-china",
    label: "美元急升、油价崩跌与中国增长担忧",
    shortLabel: "2014.06–2016.02",
    start: "2014-06-30",
    end: "2016-02-11",
    macro: "美国政策与海外宽松分化推升美元，原油供需失衡导致价格暴跌，制造业和能源资本开支衰退。",
    regime: { growth: "服务稳、制造弱", inflation: "能源拖至低位", policy: "结束 QE，2015 年首次加息", credit: "能源高收益债显著恶化" },
    events: [
      { date: "2014-H2", title: "原油价格崩跌", impact: "能源现金流和资本开支收缩，同时改善居民实际购买力。" },
      { date: "2015-08/2016-02", title: "中国与全球增长担忧", impact: "工业、材料和银行风险溢价上升。" },
    ],
    mechanism: "美元升值与商品通缩打击能源、材料和跨国工业；消费受低油价支持，医疗、必需消费与科技现金流更稳。",
    expectedLeaders: ["可选消费", "医疗保健", "必需消费", "信息技术"],
  },
  {
    id: "global-reflation-tax",
    label: "全球再通胀、减税预期与同步扩张",
    shortLabel: "2016.02–2018.01",
    start: "2016-02-11",
    end: "2018-01-26",
    macro: "商品触底、全球 PMI 同步回升，美国减税与放松监管预期进一步抬高名义增长和资本开支。",
    regime: { growth: "同步加速", inflation: "温和回升", policy: "渐进加息、后期启动缩表", credit: "宽松且违约率下降" },
    events: [
      { date: "2016-02", title: "商品与全球制造业触底", impact: "资源、工业和信用周期同步反转。" },
      { date: "2017-12", title: "税改落地", impact: "下调企业税率并提高税后利润与资本回流预期。" },
    ],
    mechanism: "名义增长、收益率和贷款需求共振利好金融、工业、材料和能源；科技仍受全球需求和盈利复利支持。",
    expectedLeaders: ["金融", "工业", "材料", "能源", "信息技术"],
  },
  {
    id: "qt-trade-tightening",
    label: "同步紧缩、贸易摩擦与增长预期下修",
    shortLabel: "2018.01–2018.12",
    start: "2018-01-26",
    end: "2018-12-24",
    macro: "Fed 加息与缩表并行，美元和实际利率上升；贸易摩擦、海外增长放缓和油价下跌共同收紧金融条件。",
    regime: { growth: "高位回落", inflation: "温和、后期下降", policy: "加息至 2.25%–2.5% + QT", credit: "利差走阔、流动性收紧" },
    events: [
      { date: "2018-H1", title: "贸易摩擦升级", impact: "供应链、资本开支和全球制造业预期受损。" },
      { date: "2018-12-19", title: "年内第四次加息", impact: "市场认为政策相对增长前景过紧，风险资产加速下跌。" },
    ],
    mechanism: "融资条件收紧先压制高杠杆和周期板块；稳定需求行业相对占优，但指数级抛售中绝对收益仍可能为负。",
    expectedLeaders: ["公用事业", "医疗保健", "必需消费"],
  },
  {
    id: "powell-pivot-late-cycle",
    label: "Powell 转向、保险式降息与晚周期延长",
    shortLabel: "2018.12–2020.02",
    start: "2018-12-24",
    end: "2020-02-19",
    macro: "Fed 从继续紧缩转向耐心，并在 2019 年三次降息；消费和服务保持韧性，制造业与全球贸易偏弱。",
    regime: { growth: "低速但未衰退", inflation: "低于目标", policy: "停止加息、结束 QT、保险式降息", credit: "重新宽松" },
    events: [
      { date: "2019-01", title: "政策转向耐心", impact: "尾部紧缩风险下降，估值与信用利差快速修复。" },
      { date: "2019-07/10", title: "三次保险式降息", impact: "延长扩张并压低长久期资产折现率。" },
    ],
    mechanism: "增长不强但贴现率下降，盈利质量和久期重新占优，科技与通信更容易获得估值扩张；能源受需求弱和供给约束较少拖累。",
    expectedLeaders: ["信息技术", "通信服务", "可选消费"],
  },
  {
    id: "covid-crash",
    label: "疫情停摆、美元荒与无差别抛售",
    shortLabel: "2020.02–2020.03",
    start: "2020-02-19",
    end: "2020-03-23",
    macro: "公共卫生冲击突然切断线下活动和现金流，国债、信用和货币基金均出现流动性压力。",
    regime: { growth: "骤停", inflation: "需求冲击主导下行", policy: "紧急降息至零并启动大规模工具", credit: "流动性冻结" },
    events: [
      { date: "2020-03-15", title: "零利率与大规模购债", impact: "政策先修复核心市场功能，再向实体信用传导。" },
      { date: "2020-03-23", title: "开放式资产购买与信用工具", impact: "公共资产负债表为市场流动性提供明确底线。" },
    ],
    mechanism: "现金流中断使高固定成本、高杠杆和出行相关行业首当其冲；必需消费、医疗与数字化需求提供相对保护。",
    expectedLeaders: ["必需消费", "医疗保健", "信息技术", "公用事业"],
  },
  {
    id: "policy-rescue-stayhome",
    label: "政策救援、居家经济与估值重建",
    shortLabel: "2020.03–2020.11",
    start: "2020-03-23",
    end: "2020-11-09",
    macro: "货币、财政和信用担保空前协同，居民转移支付托住收入；线下经济受限而数字需求提前兑现。",
    regime: { growth: "深跌后技术性反弹", inflation: "低位", policy: "零利率、QE、CARES 与信用工具", credit: "从冻结转为政策托底" },
    events: [
      { date: "2020-03-27", title: "CARES Act", impact: "财政转移、失业救济和企业支持弥补私人现金流缺口。" },
      { date: "2020-Q2/Q3", title: "远程办公与电商渗透跃升", impact: "数字基础设施、云和平台盈利预期上修。" },
    ],
    mechanism: "收入被政策托住而消费渠道转线上，科技、通信和电商型可选消费同时受益于盈利上修与低利率估值扩张。",
    expectedLeaders: ["信息技术", "可选消费", "通信服务"],
  },
  {
    id: "vaccine-reopening-reflation",
    label: "疫苗、重启、库存重建与再通胀",
    shortLabel: "2020.11–2021.11",
    start: "2020-11-09",
    end: "2021-11-19",
    macro: "疫苗降低重启尾部风险，财政继续扩张，商品需求、库存重建和供应瓶颈共同推高名义增长与通胀。",
    regime: { growth: "高速复苏", inflation: "快速上行", policy: "财政货币仍极宽松、后期讨论 Taper", credit: "宽松、贷款损失预期下降" },
    events: [
      { date: "2020-11-09", title: "疫苗有效性突破", impact: "资金从居家赢家向线下、金融、能源和小盘轮动。" },
      { date: "2021-H1", title: "财政刺激与供应瓶颈叠加", impact: "商品、运价、工资和库存需求同步抬升。" },
    ],
    mechanism: "收益率曲线变陡、贷款损失下降利好金融；出行恢复和供给纪律利好能源，工业和材料受库存与资本开支推动。",
    expectedLeaders: ["能源", "金融", "工业", "材料"],
  },
  {
    id: "inflation-fed-repricing",
    label: "通胀失控、Taper 加速与加息重定价",
    shortLabel: "2021.11–2022.06",
    start: "2021-11-19",
    end: "2022-06-16",
    macro: "高通胀从商品扩散到住房和服务，Fed 放弃暂时性判断并快速转鹰；俄乌冲突再添能源和食品供给冲击。",
    regime: { growth: "仍扩张但预期下修", inflation: "全面高企", policy: "结束 QE、启动加息与 QT", credit: "由宽松转紧" },
    events: [
      { date: "2021-11/12", title: "政策叙事转鹰", impact: "市场开始前置定价更快 Taper 和更多加息。" },
      { date: "2022-02/06", title: "战争供给冲击与 75bp 加息", impact: "通胀风险进一步压过增长，实际利率快速上升。" },
    ],
    mechanism: "高现价商品和短久期现金流占优，能源拥有定价权；高估值成长受实际利率和远期盈利折现双重压制。",
    expectedLeaders: ["能源", "必需消费", "医疗保健", "材料"],
  },
  {
    id: "peak-inflation-terminal-rate",
    label: "连续 75bp 加息与终端利率上修",
    shortLabel: "2022.06–2022.10",
    start: "2022-06-16",
    end: "2022-10-12",
    macro: "商品通胀开始见顶，但核心通胀与就业仍强，市场持续上修终端利率并压低软着陆概率。",
    regime: { growth: "减速", inflation: "总项见顶、核心黏性", policy: "连续大幅加息 + QT", credit: "全面收紧" },
    events: [
      { date: "2022-07/09", title: "连续 75bp 加息", impact: "短端利率和美元上升，金融条件快速收紧。" },
      { date: "2022-08-26", title: "Jackson Hole 强硬表态", impact: "市场对快速转向宽松的预期被打破。" },
    ],
    mechanism: "盈利下修开始接棒估值压缩，防御行业靠需求韧性相对占优；金融虽受高利率支持，但倒挂与信用风险限制表现。",
    expectedLeaders: ["医疗保健", "必需消费", "公用事业", "能源"],
  },
  {
    id: "disinflation-bottoming",
    label: "通胀见顶、美元回落与风险资产筑底",
    shortLabel: "2022.10–2023.03",
    start: "2022-10-12",
    end: "2023-03-10",
    macro: "总通胀持续回落、供应链恢复，市场从无止境加息转向终端利率可见；增长仍韧而曲线深度倒挂。",
    regime: { growth: "韧性放缓", inflation: "回落但高于目标", policy: "加息减速、QT 持续", credit: "总体稳定、久期损失累积" },
    events: [
      { date: "2022-10/11", title: "通胀与美元拐点逐步确认", impact: "实际利率上行斜率放缓，长久期资产出现修复。" },
      { date: "2023-02", title: "政策利率升至 4.5%–4.75%", impact: "存款迁移和证券账面损失对银行压力上升。" },
    ],
    mechanism: "通胀边际下降先修复估值久期，科技和通信受益；深度倒挂与存款竞争使金融表面盈利和资产负债表风险背离。",
    expectedLeaders: ["信息技术", "通信服务", "可选消费"],
  },
  {
    id: "svb-btfp-ai",
    label: "SVB、BTFP 与生成式 AI 盈利重估",
    shortLabel: "2023.03–2023.07",
    start: "2023-03-10",
    end: "2023-07-27",
    macro: "区域银行久期和存款风险暴露，但 BTFP 阻断被迫抛售；与此同时生成式 AI 驱动算力资本开支预期。",
    regime: { growth: "韧性", inflation: "缓慢回落", policy: "继续加息至 5.25%–5.5% + 流动性定向托底", credit: "银行收紧、市场融资尚稳" },
    events: [
      { date: "2023-03-10/12", title: "SVB 关闭与 BTFP 建立", impact: "系统流动性风险被托住，但区域银行信用供给转弱。" },
      { date: "2023-05", title: "AI 算力需求上修", impact: "半导体、云和平台盈利预期集中抬升。" },
    ],
    mechanism: "定向流动性工具降低系统尾部风险，却不等于全面宽松；盈利确定性集中到 AI 链，科技和通信大幅领先，金融内部显著分化。",
    expectedLeaders: ["信息技术", "通信服务", "可选消费"],
  },
  {
    id: "higher-for-longer",
    label: "Higher for Longer 与长端利率冲击",
    shortLabel: "2023.07–2023.10",
    start: "2023-07-27",
    end: "2023-10-27",
    macro: "Fed 完成最后一次加息后强调高利率维持更久，强增长、财政供给和期限溢价推动 10 年期收益率逼近 5%。",
    regime: { growth: "强于预期", inflation: "下降但黏性", policy: "5.25%–5.5% 高位平台 + QT", credit: "长端融资成本显著上升" },
    events: [
      { date: "2023-07-27", title: "政策利率到达本轮峰值区间", impact: "风险从继续加息转为高利率持续时间和长端供给。" },
      { date: "2023-10", title: "10 年期收益率逼近 5%", impact: "房地产、公用事业和高估值资产折现压力集中释放。" },
    ],
    mechanism: "高长端利率压低久期和高杠杆行业估值，能源受油价与名义增长支撑；银行受证券损失、融资成本和倒挂共同约束。",
    expectedLeaders: ["能源", "金融", "工业"],
  },
  {
    id: "pivot-ai-broadening",
    label: "降息预期、AI 资本开支与盈利上修",
    shortLabel: "2023.10–2024.07",
    start: "2023-10-27",
    end: "2024-07-16",
    macro: "通胀继续回落、市场预期下一步是降息；经济维持扩张，AI 基础设施投资转化为头部公司的盈利上修。",
    regime: { growth: "稳健扩张", inflation: "继续回落", policy: "高位暂停、转向讨论降息", credit: "市场融资宽松、银行信贷偏紧" },
    events: [
      { date: "2023-12", title: "FOMC 转向讨论降息", impact: "尾部利率风险下降，金融条件迅速放松。" },
      { date: "2024-H1", title: "AI 资本开支持续上修", impact: "算力、网络、云和电力需求形成可验证订单链。" },
    ],
    mechanism: "科技与通信由估值扩张升级为盈利驱动；数据中心需求逐步外溢到电力、公用事业和工业设备，但指数集中度上升。",
    expectedLeaders: ["信息技术", "通信服务", "公用事业", "工业"],
  },
  {
    id: "growth-scare-first-cut",
    label: "就业降温、增长担忧与首次降息前夜",
    shortLabel: "2024.07–2024.09",
    start: "2024-07-16",
    end: "2024-09-18",
    macro: "通胀改善让政策空间打开，就业和部分活动数据降温使风险平衡从单防通胀转向兼顾增长。",
    regime: { growth: "边际降温", inflation: "明显改善", policy: "高位等待后准备降息", credit: "总体可用、利率敏感需求偏弱" },
    events: [
      { date: "2024-08", title: "就业降温触发增长担忧", impact: "市场下调短端利率并从集中成长向防御和利率敏感板块轮动。" },
      { date: "2024-09-18", title: "首次降息 50bp", impact: "Fed 明确将风险平衡转向就业与通胀双向管理。" },
    ],
    mechanism: "利率下行利好公用事业、房地产和高股息，增长担忧则压制周期品；科技内部由高估值领涨转向盈利质量筛选。",
    expectedLeaders: ["公用事业", "房地产", "医疗保健", "必需消费"],
  },
  {
    id: "easing-soft-landing",
    label: "首轮降息、软着陆与再通胀交易",
    shortLabel: "2024.09–2025.01",
    start: "2024-09-18",
    end: "2025-01-29",
    macro: "Fed 连续降息至 4.25%–4.5%，增长保持韧性；长端利率因名义增长、期限溢价和政策预期重新上行。",
    regime: { growth: "韧性扩张", inflation: "高于目标但较峰值低", policy: "累计降息 100bp、QT 持续", credit: "总体宽松" },
    events: [
      { date: "2024-09/12", title: "三次降息", impact: "短端融资压力下降，但长端并未同步下行。" },
      { date: "2024-Q4", title: "软着陆与名义增长重定价", impact: "周期、金融和盈利敏感板块重新获得相对支撑。" },
    ],
    mechanism: "短端宽松与增长韧性有利金融、工业和可选消费；长端回升限制房地产、公用事业的单纯久期交易。",
    expectedLeaders: ["金融", "工业", "可选消费", "信息技术"],
  },
  {
    id: "policy-uncertainty-pause",
    label: "政策不确定性、通胀再抬头与降息暂停",
    shortLabel: "2025.01–2025.09",
    start: "2025-01-29",
    end: "2025-09-17",
    macro: "增长上半年放缓，关税与供给政策提高通胀和企业规划不确定性；Fed 在 4.25%–4.5% 观望，风险转为滞胀式双向。",
    regime: { growth: "由稳健转温和", inflation: "再度抬头", policy: "暂停降息、维持温和限制性", credit: "尚稳但企业更谨慎" },
    events: [
      { date: "2025-H1", title: "贸易与政府政策不确定性上升", impact: "库存、净出口和企业资本配置受到一次性扰动。" },
      { date: "2025-09-17", title: "Fed 重启降息 25bp", impact: "就业下行风险上升，风险平衡重新偏向增长。" },
    ],
    mechanism: "政策冲击同时影响成本、需求和利率，单一增长/通胀象限解释力下降；定价权、国内供应链与盈利可见性更重要。",
    expectedLeaders: ["信息技术", "通信服务", "医疗保健", "必需消费"],
  },
  {
    id: "renewed-cuts-dual-risk",
    label: "就业风险上升、连续降息与双向约束",
    shortLabel: "2025.09–2026.01",
    start: "2025-09-17",
    end: "2026-01-28",
    macro: "就业风险上升促使 Fed 连续三次降息至 3.5%–3.75%，但通胀仍高于目标，政策逐步接近更中性的区域。",
    regime: { growth: "温和扩张", inflation: "偏高且黏性", policy: "三次 25bp 降息", credit: "融资条件改善" },
    events: [
      { date: "2025-09/10/12", title: "连续三次降息", impact: "短端利率下移，缓冲劳动力市场和信用下行风险。" },
      { date: "2025-12", title: "进一步降息分歧扩大", impact: "市场开始重新权衡通胀黏性与就业下行的非对称风险。" },
    ],
    mechanism: "融资条件改善支持利率敏感与周期板块，但通胀黏性限制估值扩张；具备盈利增长和定价权的行业更占优。",
    expectedLeaders: ["信息技术", "工业", "金融", "可选消费"],
  },
  {
    id: "supply-shock-hold",
    label: "暂停降息、供应冲击与资本开支韧性",
    shortLabel: "2026.01–至今",
    start: "2026-01-28",
    end: "2099-12-31",
    macro: "经济保持扩张、生产率与资本投资较强，但能源等供应冲击使通胀仍高于 2%；Fed 在 3.5%–3.75% 暂停并出现更强分歧。",
    regime: { growth: "稳健扩张", inflation: "受供应冲击保持偏高", policy: "停止降息、维持利率区间", credit: "总体可用" },
    events: [
      { date: "2026-H1", title: "资本投资与生产率保持强劲", impact: "AI、电力和工业资本开支链继续支撑盈利。" },
      { date: "2026-07-29", title: "Fed 维持 3.5%–3.75%", impact: "通胀风险使进一步宽松受限，委员分歧转向是否需要更紧。" },
    ],
    mechanism: "强资本开支利好科技、工业和电力链；能源供应冲击支撑资源盈利，却可能重新抬高贴现率并压制高估值久期。",
    expectedLeaders: ["信息技术", "工业", "能源", "公用事业"],
    caveat: "开放阶段会自动以最新可得交易日截断；其排序仍在变化，不应视为已完成周期。",
  },
] as const;
