"use client";
import { useEffect, useMemo, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import Link from "next/link";
import dynamic from "next/dynamic";
import type { EconomicTransaction, OwnershipMonitorResult } from "@/lib/equity/ownershipEngine";
import { TRANSACTION_LABELS } from "@/lib/equity/ownershipSupply";
import { OwnershipReviewEditor } from "./OwnershipReviewEditor";
import type { ReviewPayload } from "@/lib/equity/ownershipTypes";
const Chart=dynamic(()=>import('echarts-for-react'),{ssr:false});
const panel="rounded-xl border border-fs-border bg-fs-surface p-5";
const field="rounded-lg border border-fs-border bg-fs-elevated px-3 py-2 text-sm";
const fmt=(n:number|null|undefined)=>n==null?'—':n.toLocaleString('zh-CN',{maximumFractionDigits:2});
const pct=(n:number|null|undefined)=>n==null?'—':`${(n*100).toFixed(2)}%`;
const statuses={included:'计入经济交易',pending:'待审核',duplicate:'重复申报',superseded:'已被更正',excluded:'已排除'};
const roles:Record<string,string>={'Founder / Executive':'创始人 / 高管',Executive:'高管',Director:'董事','VC / PE':'VC / PE','Strategic investor':'战略投资者','10% owner':'10% 持有人',Employee:'员工',Unclassified:'未分类'};
function Source({url,children}:{url:string;children:React.ReactNode}){return <a className="text-fs-accent" href={url} target="_blank" rel="noreferrer">{children} ↗</a>;}
function transactionUrl(t:EconomicTransaction){return `https://www.sec.gov/Archives/edgar/data/${Number(t.cik)}/${t.accession.replace(/-/g,'')}/${t.accession}-index.html`;}
function signal(t:EconomicTransaction){return t.transactionCode==='P'?'买入关注':t.transactionCode==='S'?(t.planStatus==='yes'?'计划执行':t.planStatus==='no'?'未申报为计划交易':'计划性质未知'):['A','M','F','G','C'].includes(t.transactionCode)?'机械 / 非市场交易':'需读脚注';}
export function OwnershipClient(){
 const params=useSearchParams(),router=useRouter();
 const symbol=(params.get('symbol')||'CRWV').trim().toUpperCase();
 const [draft,setDraft]=useState(symbol),[asOf,setAsOf]=useState(new Date().toISOString().slice(0,10)),[days,setDays]=useState(365);
 const [data,setData]=useState<(OwnershipMonitorResult&{name:string})|null>(null),[error,setError]=useState(''),[reload,setReload]=useState(0);
 const [tab,setTab]=useState('overview'),[security,setSecurity]=useState(''),[holder,setHolder]=useState(''),[code,setCode]=useState(''),[status,setStatus]=useState('');
 const [selected,setSelected]=useState<string[]>([]),[page,setPage]=useState(0),[admin,setAdmin]=useState(false),[reviewSeed,setReviewSeed]=useState<ReviewPayload|undefined>(undefined);
 const from=useMemo(()=>new Date(Date.parse(asOf||new Date().toISOString().slice(0,10))-(days-1)*86400000).toISOString().slice(0,10),[asOf,days]);
 useEffect(()=>{fetch('/api/auth/me').then(r=>r.json()).then(j=>setAdmin(j.user?.role==='admin')).catch(()=>{});},[]);
 useEffect(()=>{
  const abort=new AbortController();setData(null);setError('');setDraft(symbol);setSelected([]);setPage(0);
  if(!/^[A-Z0-9.\-]{1,16}$/.test(symbol)){setError('请输入有效美股代码');return;}
  fetch(`/api/equity/stocks/${encodeURIComponent(symbol)}/ownership?asOf=${asOf}&from=${from}`,{signal:abort.signal})
   .then(async r=>{const j=await r.json();if(!r.ok)throw new Error(j.error);return j;})
   .then(j=>{setData(j);setSecurity(prev=>j.supply.some((s:{security:string})=>s.security===prev)?prev:j.supply[0]?.security??'');})
   .catch(e=>{if(!abort.signal.aborted)setError(e.message||'读取失败');});
  return()=>abort.abort();
 },[symbol,asOf,from,reload]);
 useEffect(()=>{setPage(0);},[holder,security,code,status,tab]);
 const supply=data?.supply.find(s=>s.security===security);
 const rows=(data?.transactions??[]).filter(t=>(!security||t.security===security)&&(!holder||t.owner===holder)&&(!code||t.transactionCode===code)&&(!status||t.status===status));
 const shown=tab==='audit'?rows.filter(t=>t.status!=='included'):rows;
 const accounts=(data?.accounts??[]).filter(a=>(!security||a.security===security)&&(!holder||a.owner===holder));
 const owners=[...new Map((data?.transactions??[]).map(t=>[t.owner,t.filerName??t.owner])).entries()];
 const chartAccount=accounts.find(a=>!a.issues.length)??accounts[0];
 const [accountChoice,setAccountChoice]=useState('');
 const chosen=accounts.find(a=>a.account===accountChoice)??chartAccount;
 function download(){if(!data)return;const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`ownership-${symbol}-${asOf}.json`;a.click();URL.revokeObjectURL(url);}
 function review(seed:ReviewPayload){setReviewSeed(seed);setTab('review');}
 const metrics=[['90天净卖出 / 流通股',pct(supply?.supplyRatio90),supply?.reason||`流通股 ${fmt(supply?.floatShares)} · ${supply?.floatDate??'缺失'}`],['30天卖出 / 20日均量',supply?.sellingAdv30==null?'—':`${supply.sellingAdv30.toFixed(3)} ADV`,supply?.complete30?(supply?.advReason||`ADV ${fmt(data?.market.adv20)} · ${data?.market.latest??''}`):'窗口覆盖或经济去重尚未通过'],['90天已确认净卖出',fmt(supply?.netSells90),`卖出 ${fmt(supply?.sells90)} − 买入 ${fmt(supply?.buys90)} 股`],['待裁定记录',data?String(data.auditCount):'—','原始申报始终保留；未决行不混入确认总量']];
 return <div className="mx-auto w-full max-w-[1600px] space-y-5 px-4 py-6 text-fs-text md:px-8">
 <header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs tracking-widest text-fs-accent">OWNERSHIP & SUPPLY MONITOR</p><h1 className="mt-2 text-3xl font-semibold">持股与供给监控</h1><p className="mt-2 text-sm text-fs-muted">追踪实际持有账户、累计退出与未来计划供给</p></div><form className="flex gap-2" onSubmit={e=>{e.preventDefault();setHolder('');router.push(`/equity/ownership?symbol=${encodeURIComponent(draft.trim().toUpperCase())}`);}}><input aria-label="美股代码" className={`${field} w-32 uppercase`} value={draft} onChange={e=>setDraft(e.target.value)} maxLength={16} required/><button className="rounded-lg bg-fs-accent px-4 py-2 text-sm text-white">查看标的</button></form></header>
 <div className="flex flex-wrap items-center gap-3"><strong className="text-xl">{symbol}</strong><span className="text-sm text-fs-muted">{data?.name}</span><label className="text-sm">截至 <input aria-label="截至日期" className={field} type="date" max={new Date().toISOString().slice(0,10)} value={asOf} onChange={e=>{if(e.target.value)setAsOf(e.target.value);}}/></label><select aria-label="显示窗口" className={field} value={days} onChange={e=>setDays(Number(e.target.value))}><option value={30}>明细最近30天</option><option value={90}>明细最近90天</option><option value={365}>明细最近一年</option><option value={3650}>明细最近十年</option></select><Link className="text-sm text-fs-accent" href={`/equity/stocks/${encodeURIComponent(symbol)}`}>个股研究 ↗</Link><button onClick={download} disabled={!data} className={`${field} ml-auto`}>导出审计数据</button></div>
 {error?<div role="alert" className={panel}>{error}<button className="ml-4 text-fs-accent" onClick={()=>setReload(v=>v+1)}>重试</button></div>:!data?<p role="status">正在读取持仓、经济交易和计划证据…</p>:null}
 {data?<div className="flex flex-wrap gap-2 text-xs text-fs-muted"><span className="rounded-full border border-fs-border px-3 py-1">SEC 同步 {data.coverage?.checkedAt?.slice(0,16)??'尚未运行'}</span><span className="rounded-full border border-fs-border px-3 py-1">覆盖 {data.coverage?.since??'—'} → {data.coverage?.through??'—'} · {data.coverage?.complete?'索引内申报已处理':'不完整'}</span><span className="rounded-full border border-fs-border px-3 py-1">历史视图按披露日重建 · 使用当前已核实证据版本</span>{data.truncated?<strong className="text-amber-500">已达到读取上限，指标停用</strong>:null}</div>:null}
 <div className="flex flex-wrap gap-3"><select className={`${field} max-w-full`} aria-label="证券类别" value={security} onChange={e=>setSecurity(e.target.value)}><option value="">全部证券（不混算供给比例）</option>{data?.supply.map(s=><option key={s.security} value={s.security}>{s.security}</option>)}</select><select className={`${field} max-w-full`} aria-label="持有人" value={holder} onChange={e=>setHolder(e.target.value)}><option value="">全部持有人</option>{owners.map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></div>
 <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{metrics.map(([label,value,note])=><section key={label} className={panel}><p className="text-sm text-fs-muted">{label}</p><p className="my-3 text-3xl font-semibold tabular-nums">{value}</p><p className="text-xs leading-5 text-fs-muted">{note}</p></section>)}</div>
 <p className="text-xs leading-6 text-fs-muted">供给卡片固定为所选证券全体内部人的30/90天窗口，不随持有人筛选变化。股数统一到截至日拆股口径；流通股是有日期的估计值。已确认部分不代表市场全部供给。{supply?.floatSource?<Source url={supply.floatSource}>流通股来源</Source>:null}</p>
 <div role="tablist" aria-label="监控视图" className="flex flex-wrap gap-2">{[['overview','持仓与累计减持'],['transactions','交易明细'],['audit','经济去重审计'],['plans','10b5-1 与未来供给'],...(admin?[['review','证据审核']]:[])].map(([id,label])=><button key={id} role="tab" aria-selected={tab===id} className={`${field} ${tab===id?'text-fs-accent ring-1 ring-fs-accent':'text-fs-muted'}`} onClick={()=>setTab(id)}>{label}</button>)}</div>
 {tab==='overview'?<>
 <section className={panel}><h2 className="font-semibold">谁在退出 · 持有人类别</h2><p className="my-2 text-xs text-fs-muted">所选明细窗口内已确认交易；按证券分别统计，身份以申报或审核证据为准。</p><div className="flex flex-wrap gap-4">{data?.roleSelling.filter(r=>!security||r.security===security).map(r=><article key={`${r.security}:${r.role}`} className="rounded-lg border border-fs-border p-3"><strong>{roles[r.role]??r.role}</strong><p className="text-xs text-fs-muted">{r.security}</p><p className="mt-2 text-sm">净卖出 {fmt(r.net)} 股</p><p className="text-xs text-fs-muted">卖出 {fmt(r.shares)} · 买入 {fmt(r.buys)}</p></article>)}</div></section>
 <section className={panel}><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="font-semibold">实际持有账户 · 持仓曲线</h2><select aria-label="曲线账户" className={`${field} max-w-full`} value={chosen?.account??''} onChange={e=>setAccountChoice(e.target.value)}><option value="">选择账户</option>{accounts.map(a=><option key={`${a.account}:${a.security}`} value={a.account}>{a.name} · {a.account} · {a.security}</option>)}</select></div>{chosen?<><p className="mt-3 text-xs leading-6 text-fs-muted">{chosen.baselineDate} · {chosen.baselineLabel}；最近持股观测 {chosen.currentDate}。{chosen.inferred?'起点是首笔交易前推算值，不是IPO或解禁持仓。':''}</p><Chart style={{height:320}} option={{tooltip:{trigger:'axis'},grid:{left:85,right:30,bottom:40},xAxis:{type:'time'},yAxis:{type:'value',name:'截至日口径股数',scale:true},series:[{type:chosen.issues.length?'scatter':'line',step:'end',showSymbol:true,data:chosen.points.map(p=>[p.date,p.shares]),itemStyle:{color:'#38bdf8'}}]}}/>{chosen.issues.length?<p className="text-sm leading-6 text-amber-500">持仓未通过对账，显示观察点并暂停比例：{chosen.issues.join('；')}</p>:null}</>:<p className="py-12 text-center text-fs-muted">没有可重建的持有账户</p>}</section>
 <section className={panel}><h2 className="mb-4 font-semibold">已经卖掉多少起始持仓？</h2><div className="overflow-x-auto"><table className="w-full whitespace-nowrap text-left text-sm"><thead className="text-xs text-fs-muted"><tr>{['持有人 / 账户','类别','起始持仓','最近持仓','累计出售','累计出售 / 起始','净持仓减少','留存率'].map(h=><th className="p-3" key={h}>{h}</th>)}</tr></thead><tbody>{accounts.map(a=><tr key={`${a.account}:${a.security}`} className="border-t border-fs-border"><td className="p-3">{a.name}<p className="max-w-xs truncate text-xs text-fs-muted" title={a.account}>{a.account}</p></td><td className="p-3">{roles[a.role]??a.role}</td><td className="p-3">{fmt(a.baseline)}<p className="text-xs text-fs-muted">{a.baselineDate}</p></td><td className="p-3">{fmt(a.current)}</td><td className="p-3">{fmt(a.sold)}</td><td className="p-3">{pct(a.cumulativeSoldRatio)}</td><td className="p-3">{pct(a.netReductionRatio)}</td><td className="p-3">{pct(a.retentionRatio)}{a.issues.length?<p className="text-xs text-amber-500" title={a.issues.join('；')}>对账待处理</p>:null}</td></tr>)}</tbody></table></div><p className="mt-4 text-xs leading-6 text-fs-muted">累计出售比例与净持仓减少是不同指标：授予、行权、买入和转股会改变持仓，赠予和代扣税不算公开/私下卖出。未经证据核实的身份不会归为创始人或VC/PE。</p></section>
 </>:null}
 {tab==='transactions'||tab==='audit'?<section className={panel}><div className="mb-4 flex flex-wrap gap-3"><select aria-label="交易代码" className={field} value={code} onChange={e=>setCode(e.target.value)}><option value="">全部交易性质</option>{Object.entries(TRANSACTION_LABELS).map(([c,label])=><option key={c} value={c}>{c} · {label}</option>)}</select><select aria-label="审计状态" className={field} value={status} onChange={e=>setStatus(e.target.value)}><option value="">全部审计状态</option>{Object.entries(statuses).map(([s,label])=><option key={s} value={s}>{label}</option>)}</select><span className="self-center text-sm text-fs-muted">{shown.length} 行</span>{admin&&selected.length?<button className={`${field} text-fs-accent`} onClick={()=>review({kind:'transaction',lineIds:selected,action:'merge',canonicalId:selected[0]})}>审核所选 {selected.length} 行</button>:null}</div>
 <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="whitespace-nowrap text-xs text-fs-muted"><tr>{[...(admin?['选择']:[]),'交易 / 申报日期','申报人与实际账户','性质 / 计划','股数 / 美元价格','交易后持股','经济交易与证据'].map(h=><th key={h} className="p-3">{h}</th>)}</tr></thead><tbody>{shown.slice(page*50,page*50+50).map(t=><tr className="border-t border-fs-border align-top" key={t.id}>{admin?<td className="p-3"><input aria-label={`选择交易 ${t.id}`} type="checkbox" checked={selected.includes(t.id)} onChange={e=>setSelected(v=>e.target.checked?[...v,t.id]:v.filter(id=>id!==t.id))}/></td>:null}<td className="whitespace-nowrap p-3">{t.transactionDate}<p className="text-xs text-fs-muted">{t.filedAt} · {t.evidence?.documentType??'4'}</p></td><td className="min-w-48 p-3">{t.filerName??t.filerCik}<p className="mt-1 max-w-xs break-words text-xs text-fs-muted">{t.account??'受益账户未核实'}</p><details className="mt-2 text-xs"><summary className="cursor-pointer text-fs-accent">全部申报人 / 证券</summary>{t.evidence?.owners.map(o=><p key={o.cik}>{o.name} · {o.cik}</p>)}<p>{t.security}</p></details></td><td className="min-w-40 p-3">{t.transactionCode} · {TRANSACTION_LABELS[t.transactionCode]??'其他'}<p className="mt-1 text-xs text-fs-muted">{signal(t)}</p><p className="text-xs text-fs-muted">计划建立：{t.evidence?.planAdoptionDate??'未知'}</p></td><td className="whitespace-nowrap p-3 tabular-nums">{fmt(t.shares)} · {t.acquiredDisposedCode==='D'?'处置':'取得'}<p className="text-xs text-fs-muted">${fmt(t.pricePerShare)} · 金额 ${fmt(t.pricePerShare==null?null:t.shares*t.pricePerShare)}</p></td><td className="p-3 tabular-nums">{fmt(t.sharesOwnedAfter)}</td><td className="min-w-56 p-3"><span className={t.status==='pending'?'text-amber-500':'text-fs-muted'}>{statuses[t.status]}</span><p className="mt-1 text-xs text-fs-muted">{t.reason}</p><Source url={transactionUrl(t)}>SEC 原文</Source><details className="mt-2 text-xs"><summary className="cursor-pointer text-fs-accent">脚注 / 行ID / 经济ID</summary><p className="break-all">行：{t.id}</p><p className="break-all">经济：{t.economicId}</p>{t.evidence?.footnotes.map((f,i)=><p key={i} className="mt-2 max-w-lg whitespace-pre-wrap">{f}</p>)}</details></td></tr>)}</tbody></table></div>
 {!shown.length&&data?<p className="py-12 text-center text-fs-muted">该筛选下没有记录。请查看覆盖状态；无记录不代表没有交易。</p>:null}<div className="mt-4 flex justify-end gap-3"><button className={field} disabled={page===0} onClick={()=>setPage(p=>p-1)}>上一页</button><span className="self-center text-sm">{page+1} / {Math.max(1,Math.ceil(shown.length/50))}</span><button className={field} disabled={(page+1)*50>=shown.length} onClick={()=>setPage(p=>p+1)}>下一页</button></div></section>:null}
 {tab==='plans'?<section className={panel}><h2 className="font-semibold">10b5-1 计划与潜在供给</h2><p className="my-3 text-sm leading-6 text-fs-muted">计划建立时即可显示潜在供给；上限不是成交承诺。计划可能因价格条件、归属、提前终止或与其他计划共享额度而无法全部执行。下一窗口取披露日期，不预测实际卖出日。</p><div className="grid gap-4 lg:grid-cols-2">{data?.plans.map(p=><article key={p.id} className="rounded-xl border border-fs-border p-4"><div className="flex items-center justify-between gap-3"><h3 className="font-semibold">{p.ownerName}</h3><span className="text-xs text-fs-accent">{p.status==='candidate'?'待解析':p.state}</span></div><p className="mt-2 text-xs text-fs-muted">建立 {p.adopted??'待核实'} · 披露 {p.filedAt}</p><p className="my-3 text-2xl font-semibold">{fmt(p.adjustedMaximum)} <span className="text-xs font-normal text-fs-muted">股 · 披露上限</span></p><div className="space-y-1 text-sm"><p>执行窗口：{p.start??'未披露'} → {p.end??'未披露'}</p><p>已明确关联成交：{fmt(p.linkedExecuted)} 股</p><p>剩余条件性上限：{fmt(p.remainingUpperBound)} 股</p><p>计划上限 / 对应账户持股：{pct(p.plannedHoldingRatio)}</p>{p.terminated?<p>终止日期：{p.terminated}</p>:null}</div><p className="mt-3 text-xs leading-6 text-fs-muted">{p.conditions}。{p.calculationNote}</p><Source url={p.sourceUrl}>计划原文</Source><details className="mt-2 text-xs"><summary className="cursor-pointer text-fs-accent">取证详情</summary><p className="my-2 break-all">计划 ID：{p.id}</p><p className="max-h-60 overflow-y-auto whitespace-pre-wrap leading-6">{p.evidence}</p></details>{admin?<button className={`${field} mt-3`} onClick={()=>review({kind:'plan',plan:p})}>核实计划条款</button>:null}</article>)}</div>{data&&!data.plans.length?<p className="py-12 text-center text-fs-muted">已入库财报中尚未提取计划，请检查财报覆盖；此处不将未知供给记为0。</p>:null}</section>:null}
 {tab==='review'&&admin&&data?<OwnershipReviewEditor key={JSON.stringify(reviewSeed)} symbol={symbol} data={data} seed={reviewSeed} onSaved={()=>{setReload(v=>v+1);setTab('audit');}}/>:null}
 <footer className="text-xs leading-6 text-fs-muted">申报事实来自 SEC EDGAR，Form 3/4/5、修订与财报计划沿同一同步链更新。重复和更正按行审核；同值不自动等同同一经济交易。持有账户分开对账，不把同一受益链的多个申报人累加。<Source url="https://www.sec.gov/resources-small-businesses/small-business-compliance-guides/insider-trading-arrangements-and-related-disclosures">SEC 计划披露说明</Source></footer>
 </div>;
}
