/** 国家统计局固定资产投资：月度累计同比、年度名义值/同比，另设官方总项环比。 */
import { loadEnvConfig } from "@next/env";
import { DataFetchMethod, DataGranularity, InstrumentKind, PrismaClient, SourceAdapterKind } from "@prisma/client";
import { mergeFetchAcquisition } from "../../src/lib/data/scheduler/fetchAcquisition";
import { computeNextRunAt, defaultEconomicCalendarRule } from "../../src/lib/data/scheduler/releaseRule";
import { fetchLatestFaiMom, fetchNbsFaiCatalog } from "../../src/lib/data/scheduler/nbsFai/client";
import { NBS_FAI_DATA_URL, NBS_FAI_MOM_CODE, NBS_FAI_RELEASE_INDEX_URL, NBS_FAI_SOURCE, NBS_FAI_SYNC_SCRIPT, nbsFaiCode } from "../../src/lib/data/scheduler/nbsFai/catalog";
loadEnvConfig(process.cwd()); const prisma = new PrismaClient();
async function main() {
  await prisma.statisticalAgency.upsert({ where: { id: "cn-nbs" }, create: { id: "cn-nbs", countryCode: "CN", nameZh: "国家统计局", nameEn: "National Bureau of Statistics of China", websiteUrl: "https://www.stats.gov.cn/" }, update: { countryCode: "CN", nameZh: "国家统计局", nameEn: "National Bureau of Statistics of China", websiteUrl: "https://www.stats.gov.cn/" } });
  await prisma.dataSource.upsert({ where: { id: NBS_FAI_SOURCE.id }, create: { ...NBS_FAI_SOURCE, adapterKind: SourceAdapterKind.REST_API, rateLimit: { requestsPerMinute: 6, minIntervalMs: 1000 } }, update: { agencyId: "cn-nbs", name: NBS_FAI_SOURCE.name, adapterKind: SourceAdapterKind.REST_API, baseUrl: NBS_FAI_SOURCE.baseUrl, termsUrl: NBS_FAI_SOURCE.termsUrl, rateLimit: { requestsPerMinute: 6, minIntervalMs: 1000 } } });
  const entries = await fetchNbsFaiCatalog(); const mom = await fetchLatestFaiMom(); const probedAt = new Date().toISOString();
  for (const item of entries) { const code = nbsFaiCode(item.frequency, item.cid, item.indicatorId); const granularity = item.frequency === "monthly" ? DataGranularity.MONTHLY : DataGranularity.ANNUAL; const rule = defaultEconomicCalendarRule(granularity); const old = await prisma.instrument.findUnique({ where: { code }, select: { metadata: true } }); const metadata = mergeFetchAcquisition({ ...(old?.metadata as Record<string, unknown> ?? {}), sourceTag: "nbs-fai-official-data", bootstrapOnly: false, source: "国家统计局", providerNote: "National Bureau of Statistics of China", sourceUrl: NBS_FAI_DATA_URL, officialUrl: NBS_FAI_RELEASE_INDEX_URL, countryCode: "CN", countryNameZh: "中国", displayName: `固定资产投资：${item.label}`, catalogCategory: "固定资产投资", freqLabel: item.frequency === "monthly" ? "月" : "年", unit: item.unit, sourceUpdateNote: item.frequency === "monthly" ? "国家数据公开接口：固定资产投资月度分项为累计同比；1 月免报。" : "国家数据公开接口：年度名义金额（亿元）及同比增长。", scrape: { provider: "nbs_fai", ...item, script: NBS_FAI_SYNC_SCRIPT } }, { status: "known", probedAt, method: "nbs_fai_official_nbs_data", methodLabel: NBS_FAI_SYNC_SCRIPT, fetchUrl: NBS_FAI_DATA_URL, officialUrl: NBS_FAI_RELEASE_INDEX_URL, message: "国家统计局国家数据 UUID 接口；月度发布稿补充总项季调环比。" });
    const instrument = await prisma.instrument.upsert({ where: { code }, create: { code, kind: InstrumentKind.MACRO_SERIES, name: `中国：固定资产投资：${item.label}`, shortName: `固投：${item.label}`, description: `国家统计局${item.frequency === "monthly" ? "月度" : "年度"}${item.label}`, freqLabel: item.frequency === "monthly" ? "月" : "年", unit: item.unit, metadata: metadata as object, externalRefs: { catalogKey: `mds:${code}`, agencyId: "cn-nbs", sourceId: NBS_FAI_SOURCE.id } }, update: { name: `中国：固定资产投资：${item.label}`, shortName: `固投：${item.label}`, description: `国家统计局${item.frequency === "monthly" ? "月度" : "年度"}${item.label}`, freqLabel: item.frequency === "monthly" ? "月" : "年", unit: item.unit, metadata: metadata as object } });
    await prisma.dataSubscription.upsert({ where: { instrumentId: instrument.id }, create: { instrumentId: instrument.id, sourceId: NBS_FAI_SOURCE.id, sourceSeriesKey: `${item.frequency}:${item.cid}:${item.indicatorId}`, fetchMethod: DataFetchMethod.API, granularity, releaseRule: rule as object, nextRunAt: computeNextRunAt(rule, new Date()), enabled: true, priority: 42 }, update: { sourceId: NBS_FAI_SOURCE.id, sourceSeriesKey: `${item.frequency}:${item.cid}:${item.indicatorId}`, fetchMethod: DataFetchMethod.API, granularity, releaseRule: rule as object, nextRunAt: computeNextRunAt(rule, new Date()), enabled: true, priority: 42 } });
  }
  const rule = defaultEconomicCalendarRule(DataGranularity.MONTHLY); const old = await prisma.instrument.findUnique({ where: { code: NBS_FAI_MOM_CODE }, select: { metadata: true } }); const momMetadata = mergeFetchAcquisition({ ...(old?.metadata as Record<string, unknown> ?? {}), sourceTag: "nbs-fai-official-release", bootstrapOnly: false, source: "国家统计局", providerNote: "National Bureau of Statistics of China", sourceUrl: mom.articleUrl, officialUrl: NBS_FAI_RELEASE_INDEX_URL, countryCode: "CN", countryNameZh: "中国", displayName: "固定资产投资（不含农户）：季调环比", catalogCategory: "固定资产投资", freqLabel: "月", unit: "%", sourceUpdateNote: "国家统计局月报仅发布固定资产投资（不含农户）总项的季节调整环比，分项不发布环比，不作推算。", scrape: { provider: "nbs_fai", measure: "mom", indexUrl: NBS_FAI_RELEASE_INDEX_URL, articleUrl: mom.articleUrl, script: NBS_FAI_SYNC_SCRIPT } }, { status: "known", probedAt, method: "nbs_fai_official_release", methodLabel: NBS_FAI_SYNC_SCRIPT, fetchUrl: NBS_FAI_RELEASE_INDEX_URL, officialUrl: NBS_FAI_RELEASE_INDEX_URL, message: "国家统计局月度发布稿总项环比锚点。" });
  const instrument = await prisma.instrument.upsert({ where: { code: NBS_FAI_MOM_CODE }, create: { code: NBS_FAI_MOM_CODE, kind: InstrumentKind.MACRO_SERIES, name: "中国：固定资产投资（不含农户）：季调环比", shortName: "固定资产投资：环比", description: "国家统计局固定资产投资（不含农户）季节调整环比", freqLabel: "月", unit: "%", metadata: momMetadata as object, externalRefs: { catalogKey: `mds:${NBS_FAI_MOM_CODE}`, agencyId: "cn-nbs", sourceId: NBS_FAI_SOURCE.id } }, update: { metadata: momMetadata as object } });
  await prisma.dataSubscription.upsert({ where: { instrumentId: instrument.id }, create: { instrumentId: instrument.id, sourceId: NBS_FAI_SOURCE.id, sourceSeriesKey: "monthly:headline:mom", fetchMethod: DataFetchMethod.API, granularity: DataGranularity.MONTHLY, releaseRule: rule as object, nextRunAt: computeNextRunAt(rule, new Date()), enabled: true, priority: 42 }, update: { sourceId: NBS_FAI_SOURCE.id, fetchMethod: DataFetchMethod.API, granularity: DataGranularity.MONTHLY, releaseRule: rule as object, nextRunAt: computeNextRunAt(rule, new Date()), enabled: true, priority: 42 } });
  console.log(`[data:seed-nbs-fai] 完成：${entries.length + 1} 条官方固定资产投资订阅`);
}
main().catch((e) => { console.error(e); process.exit(1); }).finally(() => prisma.$disconnect());
