/** 国家统计局规模以上工业增加值：总项、经济类型、三大门类和 41 行业。 */
import { loadEnvConfig } from "@next/env";
import { DataFetchMethod, DataGranularity, InstrumentKind, PrismaClient, SourceAdapterKind } from "@prisma/client";
import { mergeFetchAcquisition } from "../../src/lib/data/scheduler/fetchAcquisition";
import { computeNextRunAt, defaultEconomicCalendarRule } from "../../src/lib/data/scheduler/releaseRule";
import { fetchLatestIndustrialMom, fetchNbsIndustrialCurrentCatalog } from "../../src/lib/data/scheduler/nbsIndustrial/client";
import { NBS_INDUSTRIAL_COMPONENTS, NBS_INDUSTRIAL_INDEX_URL, NBS_INDUSTRIAL_SOURCE, NBS_INDUSTRIAL_SYNC_SCRIPT, nbsIndustrialCode, type IndustrialMeasure } from "../../src/lib/data/scheduler/nbsIndustrial/catalog";
loadEnvConfig(process.cwd()); const prisma = new PrismaClient();
const measures: readonly { key: IndustrialMeasure; label: string }[] = [{ key: "yoy", label: "同比" }, { key: "cumulative_yoy", label: "累计同比" }];
async function main() {
  // 早期实现曾把 `cumulative_yoy` 原样写入 code，部分长行业名超过数据库 48 字符限制。
  // 仅清理这个尚未发布的、可精确识别的旧命名前缀，观测和订阅会随关系级联删除。
  const legacy = await prisma.instrument.deleteMany({ where: { code: { startsWith: "nbs_cn_industrial_", endsWith: "_cumulative_yoy" } } });
  if (legacy.count) console.log(`[data:seed-nbs-industrial] 清理旧超长命名 ${legacy.count} 条`);
  await prisma.statisticalAgency.upsert({ where: { id: "cn-nbs" }, create: { id: "cn-nbs", countryCode: "CN", nameZh: "国家统计局", nameEn: "National Bureau of Statistics of China", websiteUrl: "https://www.stats.gov.cn/" }, update: { countryCode: "CN", nameZh: "国家统计局", nameEn: "National Bureau of Statistics of China", websiteUrl: "https://www.stats.gov.cn/" } });
  await prisma.dataSource.upsert({ where: { id: NBS_INDUSTRIAL_SOURCE.id }, create: { id: NBS_INDUSTRIAL_SOURCE.id, agencyId: "cn-nbs", name: NBS_INDUSTRIAL_SOURCE.name, adapterKind: SourceAdapterKind.REST_API, baseUrl: NBS_INDUSTRIAL_SOURCE.baseUrl, termsUrl: NBS_INDUSTRIAL_SOURCE.termsUrl, rateLimit: { requestsPerMinute: 6, minIntervalMs: 1000 } }, update: { agencyId: "cn-nbs", name: NBS_INDUSTRIAL_SOURCE.name, adapterKind: SourceAdapterKind.REST_API, baseUrl: NBS_INDUSTRIAL_SOURCE.baseUrl, termsUrl: NBS_INDUSTRIAL_SOURCE.termsUrl, rateLimit: { requestsPerMinute: 6, minIntervalMs: 1000 } } });
  const catalog = await fetchNbsIndustrialCurrentCatalog(); const mom = await fetchLatestIndustrialMom(); const rule = defaultEconomicCalendarRule(DataGranularity.MONTHLY); const nextRunAt = computeNextRunAt(rule, new Date()); const probedAt = new Date().toISOString();
  const entries = NBS_INDUSTRIAL_COMPONENTS.flatMap((component) => measures.map((measure) => ({ component, measure }))).concat([{ component: NBS_INDUSTRIAL_COMPONENTS[0]!, measure: { key: "mom" as const, label: "环比" } }]);
  for (const { component, measure } of entries) {
    const code = nbsIndustrialCode(component.key, measure.key); const source = measure.key === "mom" ? null : catalog.get(`${component.key}:${measure.key}`); if (measure.key !== "mom" && !source) throw new Error(`工业增加值目录缺少 ${component.key}:${measure.key}`);
    const previous = await prisma.instrument.findUnique({ where: { code } }); const old = previous?.metadata && typeof previous.metadata === "object" && !Array.isArray(previous.metadata) ? previous.metadata as Record<string, unknown> : {};
    const scrape = measure.key === "mom" ? { provider: "nbs_industrial", indexUrl: NBS_INDUSTRIAL_INDEX_URL, articleUrl: mom.articleUrl, component: component.key, measure: measure.key, officialAvailability: "headline_only", script: NBS_INDUSTRIAL_SYNC_SCRIPT } : { provider: "nbs_industrial", cid: source!.cid, indicatorId: source!.indicatorId, component: component.key, componentGroup: component.group, measure: measure.key, script: NBS_INDUSTRIAL_SYNC_SCRIPT };
    const metadata = mergeFetchAcquisition({ ...old, sourceTag: "nbs-industrial-official-data", bootstrapOnly: false, source: "国家统计局", providerNote: "National Bureau of Statistics of China", sourceUrl: NBS_INDUSTRIAL_INDEX_URL, officialUrl: NBS_INDUSTRIAL_INDEX_URL, countryCode: "CN", countryNameZh: "中国", displayName: `规上工业增加值：${component.displayName}${measure.label}`, catalogCategory: "工业", freqLabel: "月", unit: "%", sourceUpdateNote: measure.key === "mom" ? "国家统计局月度发布稿仅公布规上工业增加值总项环比；分项未公开发布环比，不创建推算值。" : "国家统计局国家数据公开 UUID 接口，提供当月同比和累计同比。", scrape }, { status: "known", probedAt, method: "nbs_industrial_official_nbs_data", methodLabel: NBS_INDUSTRIAL_SYNC_SCRIPT, fetchUrl: NBS_INDUSTRIAL_INDEX_URL, officialUrl: NBS_INDUSTRIAL_INDEX_URL, message: "国家数据 UUID 接口回填同比/累计同比；月度发布稿抓取总项环比。" });
    const instrument = await prisma.instrument.upsert({ where: { code }, create: { code, kind: InstrumentKind.MACRO_SERIES, name: `中国：规上工业增加值：${component.displayName}${measure.label}`, shortName: `工业增加值：${component.displayName}${measure.label}`, description: `国家统计局规模以上工业增加值${component.displayName}${measure.label}`, freqLabel: "月", unit: "%", metadata: metadata as object, externalRefs: { catalogKey: `mds:${code}`, agencyId: "cn-nbs", sourceId: NBS_INDUSTRIAL_SOURCE.id } }, update: { name: `中国：规上工业增加值：${component.displayName}${measure.label}`, shortName: `工业增加值：${component.displayName}${measure.label}`, description: `国家统计局规模以上工业增加值${component.displayName}${measure.label}`, freqLabel: "月", unit: "%", metadata: metadata as object } });
    await prisma.dataSubscription.upsert({ where: { instrumentId: instrument.id }, create: { instrumentId: instrument.id, sourceId: NBS_INDUSTRIAL_SOURCE.id, sourceSeriesKey: `${component.key}:${measure.key}`, fetchMethod: DataFetchMethod.API, granularity: DataGranularity.MONTHLY, releaseRule: rule as object, nextRunAt, enabled: true, priority: 41 }, update: { sourceId: NBS_INDUSTRIAL_SOURCE.id, sourceSeriesKey: `${component.key}:${measure.key}`, fetchMethod: DataFetchMethod.API, granularity: DataGranularity.MONTHLY, releaseRule: rule as object, nextRunAt, enabled: true, priority: 41 } });
  }
  console.log(`[data:seed-nbs-industrial] 完成：${entries.length} 条订阅（总项环比 1 条；分项官方同比/累计同比）`);
}
main().catch((e) => { console.error(e); process.exit(1); }).finally(() => prisma.$disconnect());
