import assert from "node:assert/strict";
import { loadEnvConfig } from "@next/env";
import { PrismaClient } from "@prisma/client";
import { JP_CYCLE_LABOR_SERIES, JP_CYCLE_LABOR_SOURCE_ID } from "../../src/lib/data/scheduler/jpCycleLabor/catalog";
import { fetchJpCycleLaborWorkbook } from "../../src/lib/data/scheduler/jpCycleLabor/client";
import { parseJpCycleLaborWorkbook } from "../../src/lib/data/scheduler/jpCycleLabor/parser";
loadEnvConfig(process.cwd());
async function main() { const fixtureDir = process.argv.find((arg) => arg.startsWith("--fixture-dir="))?.slice(14); if (fixtureDir || process.argv.includes("--live")) for (const series of JP_CYCLE_LABOR_SERIES) { const name = series.source === "ci" ? "esri-ci.xlsx" : series.source === "unemployment" ? "lfs-unemployment.xlsx" : "mhlw-job-ratio.xlsx"; const points = parseJpCycleLaborWorkbook(await fetchJpCycleLaborWorkbook(series.source, fixtureDir ? `${fixtureDir}/${name}` : undefined), series); console.log("source verified", series.instrumentCode, points.length, points[0]?.obsDate.toISOString().slice(0,10), points.at(-1)?.obsDate.toISOString().slice(0,10)); } if (!process.argv.includes("--db")) return; const prisma = new PrismaClient(); try { for (const series of JP_CYCLE_LABOR_SERIES) { const inst = await prisma.instrument.findUniqueOrThrow({ where: { code: series.instrumentCode }, include: { dataSubscription: true } }); const md = inst.metadata as Record<string, unknown>; assert.equal(inst.unit, series.unit); assert.equal(inst.freqLabel, "月"); assert.equal(md.countryCode, "JP"); assert.equal(md.seasonalAdjustment, "SA"); assert.equal(inst.dataSubscription?.sourceId, JP_CYCLE_LABOR_SOURCE_ID); assert.equal((inst.dataSubscription?.releaseRule as { type?: string })?.type, "probe_interval"); const points = await prisma.macroObservation.findMany({ where: { instrumentId: inst.id }, orderBy: { obsDate: "asc" } }); assert(points.length > 450); assert(Date.now() - points.at(-1)!.obsDate.getTime() < 120 * 86_400_000); console.log("db verified", series.instrumentCode, points.length); } } finally { await prisma.$disconnect(); } }
main().catch((error) => { console.error(error instanceof Error ? error.message : "Japan cycle/labor verify failed"); process.exitCode = 1; });
